### PR TITLE
reintroduce nanotiming

### PR DESCRIPTION
**Pull request by yoshuawuyts**
cc/ @juliangruber - think this might be useful; not 100% yet, but at least
there's some introspection possible again - could you add me as an owner on npm
btw? Thanks!

### CODE REVIEW

**Comment by juliangruber** [comment]
> could you add me as an owner on npm
> btw? Thanks!

weird, how did you even get removed? Added you via CLI and Web, but `npm owner ls` doesn't list you yet.

**Comment by juliangruber** [comment]
I think this patch is more useful with according docs, as I don't know how that info would be properly consumed.

**Comment by yoshuawuyts** [comment]
I emailed npm about the ownership issue; hope it gets resolved.

Updated the patch, lmk what you think!

**Comment by yoshuawuyts** [comment]
meep, just using nanocomponent these days. No need for this :sparkles:

**Pull request closed without merging**
